
        DROP TABLE TESTDB.PUBLIC.box IF EXISTS;
        CREATE TABLE TESTDB.PUBLIC.box(id SERIAL,ACCOUNT_ID NUMBER, username VARCHAR(255), title VARCHAR(255),body VARCHAR(255),boxtype VARCHAR(255));


        DROP TABLE TESTDB.PUBLIC.account IF EXISTS;
        CREATE TABLE TESTDB.PUBLIC.account(id SERIAL, login VARCHAR(255), username VARCHAR(255), password VARCHAR(255),ava_Url VARCHAR(255), birthday DATE,created_ts TIMESTAMP,gender VARCHAR(255) );

        DROP TABLE TESTDB.PUBLIC.account_details IF EXISTS;
        CREATE TABLE TESTDB.PUBLIC.account_details(id SERIAL, ACCOUNT_ID NUMBER, DATA_TYPE VARCHAR(255), NAME VARCHAR(255),VALUE VARCHAR(255));


